In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../../../data/test.csv')

In [3]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [5]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode().iloc[0])

In [6]:
df['Embarked'].isna().sum()

np.int64(0)

In [7]:
df['Cabin'] = df['Cabin'].fillna(df['Cabin'].mode().iloc[0])

In [8]:
df['Deck'] = df['Cabin'].apply(lambda x: x[0] if pd.notnull(x) else 'M')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        418 non-null    object
 10  Embarked     418 non-null    object
 11  Deck         418 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 39.3+ KB

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [11]:
df = df.drop('Cabin', axis = 1)

In [12]:
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [13]:
df = df.drop('Name', axis = 1)

In [14]:
def title_replace(title):
    if title in ['Mlle', 'Ms']:
        return 'Miss'
    elif title == 'Mme':
        return 'Mrs'
    elif title in ['Don', 'Rev', 'Dr', 'Major', 'Lady', 'Sir', 'Col', 'Capt', 'Countess', 'Jonkheer', 'Dona']:
        return 'Rare'
    else:
        return title

In [15]:
df['Title'] = df['Title'].apply(title_replace)

In [16]:
titles_m = {'Mr': 0, 'Mrs': 1, 'Miss': 2, 'Master': 3, 'Rare': 4}
df['Title'] = df['Title'].map(titles_m)

In [17]:
def clean_ticket(ticket):
    if ticket.isdigit():
        return "Numeric"
    else:
        letters = ticket.split(' ')[0]
        letters = letters.replace('.', '').replace('/', '').upper()
        return letters

df['Ticket_Letters'] = df['Ticket'].apply(clean_ticket)

df['Ticket_Letters'].value_counts()

Ticket_Letters
Numeric    296
PC          32
CA          27
SOTONOQ      9
SCPARIS      8
A5           7
WC           5
FCC          4
SOPP         4
C            3
A4           3
SOC          2
FC           2
SCAH         2
STONO        2
STONO2       1
WEP          1
SCA3         1
PP           1
SCA4         1
STONOQ       1
SOTONO2      1
AQ4          1
A            1
SC           1
LP           1
AQ3          1
Name: count, dtype: int64

In [18]:
def ticket_replace(ticket):
    main_tickets = ['A5', 'PC', 'Numeric', 'CA', 'SCPARIS', 'WC', 'SOTONOQ', 'STONO']
    
    if ticket in main_tickets:
        return ticket
    else:
        return 'Rare'

In [19]:
df['Ticket_Letters'] = df['Ticket_Letters'].apply(ticket_replace)

In [20]:
ticket_m = {'A5': 0, 'PC': 1, 'Rare': 2, 'Numeric': 3, 'CA': 4, 'SCPARIS': 5, 'WC':  6, 'SOTONOQ': 7, 'STONO': 8}
df['Ticket_Letters'] = df['Ticket_Letters'].map(ticket_m)

In [21]:
df = df.drop('Ticket', axis = 1)

In [22]:
deck_m = {'M': 0, 'C': 1, 'E': 2, 'G': 3, 'D': 4, 'A': 5, 'B': 6, 'F': 7, 'T': 8}
embarked_m = {
    'S': 0,
    'C': 1,
    'Q': 2
}

In [23]:
df['Embarked'] = df['Embarked'].map(embarked_m)
df['Deck'] = df['Deck'].map(deck_m)

In [24]:
df.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Ticket_Letters
0,892,3,male,34.5,0,0,7.8292,2,6,0,3
1,893,3,female,47.0,1,0,7.0000,0,6,1,3
2,894,2,male,62.0,0,0,9.6875,2,6,0,3
3,895,3,male,27.0,0,0,8.6625,0,6,0,3
4,896,3,female,22.0,1,1,12.2875,0,6,1,3

In [25]:
df['Sex'] = df['Sex'].replace({
    'male': 1,
    'female': 0
})

/tmp/ipykernel_839118/3269738305.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = df['Sex'].replace({

In [26]:
df.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Ticket_Letters
0,892,3,1,34.5,0,0,7.8292,2,6,0,3
1,893,3,0,47.0,1,0,7.0000,0,6,1,3
2,894,2,1,62.0,0,0,9.6875,2,6,0,3
3,895,3,1,27.0,0,0,8.6625,0,6,0,3
4,896,3,0,22.0,1,1,12.2875,0,6,1,3

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     418 non-null    int64
 1   Pclass          418 non-null    int64
 2   Sex             418 non-null    int64
 3   Age             418 non-null    float64
 4   SibSp           418 non-null    int64
 5   Parch           418 non-null    int64
 6   Fare            417 non-null    float64
 7   Embarked        418 non-null    int64
 8   Deck            418 non-null    int64
 9   Title           418 non-null    int64
 10  Ticket_Letters  418 non-null    int64
dtypes: float64(2), int64(9)
memory usage: 36.1 KB

In [28]:
df[df['Fare'].isna() == True]

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Ticket_Letters
152,1044,3,1,60.5,0,0,NaN,0,6,0,3

In [29]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

In [30]:
import joblib

In [32]:
df.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Ticket_Letters
0,892,3,1,34.5,0,0,7.8292,2,6,0,3
1,893,3,0,47.0,1,0,7.0000,0,6,1,3
2,894,2,1,62.0,0,0,9.6875,2,6,0,3
3,895,3,1,27.0,0,0,8.6625,0,6,0,3
4,896,3,0,22.0,1,1,12.2875,0,6,1,3

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     418 non-null    int64
 1   Pclass          418 non-null    int64
 2   Sex             418 non-null    int64
 3   Age             418 non-null    float64
 4   SibSp           418 non-null    int64
 5   Parch           418 non-null    int64
 6   Fare            418 non-null    float64
 7   Embarked        418 non-null    int64
 8   Deck            418 non-null    int64
 9   Title           418 non-null    int64
 10  Ticket_Letters  418 non-null    int64
dtypes: float64(2), int64(9)
memory usage: 36.1 KB

In [35]:
df = df.drop('PassengerId', axis = 1)

In [36]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck,Title,Ticket_Letters
0,3,1,34.5,0,0,7.8292,2,6,0,3
1,3,0,47.0,1,0,7.0000,0,6,1,3
2,2,1,62.0,0,0,9.6875,2,6,0,3
3,3,1,27.0,0,0,8.6625,0,6,0,3
4,3,0,22.0,1,1,12.2875,0,6,1,3

In [37]:
model = joblib.load('my_svm_model.pkl')

In [39]:
final_prediction = model.predict(df.values)

In [44]:
submission = pd.DataFrame({
    "PassengerId": passenger_ids, 
    "Survived": final_prediction
})

print(submission.head())

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [40]:
df2 = pd.read_csv('../../../data/test.csv')

In [43]:
passenger_ids = df2['PassengerId']

In [45]:
submission.to_csv('my_svm_submission.csv', index=False)

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()

In [50]:
loaded_scaler = joblib.load('titanic_scaler.pkl')

In [51]:
df_scaled = loaded_scaler.transform(df)

In [53]:
final_pred = model.predict(df_scaled)

In [54]:
submission = pd.DataFrame({
    "PassengerId": passenger_ids, 
    "Survived": final_pred
})

print(submission.head())

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [55]:
submission.to_csv('svm_submission.csv', index=False)

In [56]:
ab_model = joblib.load('my_ab_model.pkl')

In [57]:
ab_pred = ab_model.predict(df)

In [58]:
submission_ab = pd.DataFrame({
    "PassengerId": passenger_ids, 
    "Survived": ab_pred
})

In [59]:
submission_ab.to_csv('my_ab_submission.csv', index=False)

In [60]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

In [61]:
df2 = df.drop(['FamilySize', 'SibSp'], axis = 1)

In [64]:
model_ab2 = joblib.load('my_ab_model2.pkl')

In [65]:
ab2_pred = model_ab2.predict(df2)

In [66]:
submission_ab2 = pd.DataFrame({
    "PassengerId": passenger_ids, 
    "Survived": ab2_pred
})

In [69]:
submission_ab2.to_csv('ab2_sub.csv', index=False)

In [68]:
submission_ab2

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]